// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";

function set(map, key, value) {
  map.set(key, value);
  return map;
}

function adjust(map, key, fn) {
  Stdlib_Option.map(map.get(key), val => {
    map.set(key, fn(val));
  });
  return map;
}

function $$delete(map, key) {
  map.delete(key);
  return map;
}

function filter(map, fn) {
  return new Map(map.entries().filter(param => fn(param[0], param[1])));
}

function map(map$1, fn) {
  return new Map(map$1.entries().map(param => [
    param[0],
    fn(param[1])
  ]));
}

let $$Map$1 = {
  set: set,
  adjust: adjust,
  $$delete: $$delete,
  filter: filter,
  map: map
};

export {
  $$Map$1 as $$Map,
}
/* No side effect */
