// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "rescript/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as Data$RescriptDigraph from "./Data.js";

function make() {
  return {
    vertexData: new Map(),
    adjacency: new Map(),
    nextId: 0
  };
}

function insertVertex(param, vdata) {
  let nextId = param.nextId;
  return {
    vertexData: Data$RescriptDigraph.$$Map.set(param.vertexData, nextId, vdata),
    adjacency: Data$RescriptDigraph.$$Map.set(param.adjacency, nextId, new Map()),
    nextId: nextId + 1 | 0
  };
}

function insertEdge(param, from, to, edgeData) {
  let adjacency = param.adjacency;
  let vertexData = param.vertexData;
  return {
    vertexData: vertexData,
    adjacency: vertexData.has(to) ? Data$RescriptDigraph.$$Map.adjust(adjacency, from, map => Data$RescriptDigraph.$$Map.set(map, to, edgeData)) : adjacency,
    nextId: param.nextId
  };
}

function getVertex(param, vid) {
  return param.vertexData.get(vid);
}

function getEdge(param, from, to) {
  return Stdlib_Option.flatMap(param.adjacency.get(from), map => map.get(to));
}

function mapVertices(param, fn) {
  return {
    vertexData: Data$RescriptDigraph.$$Map.map(param.vertexData, fn),
    adjacency: param.adjacency,
    nextId: param.nextId
  };
}

function mapEdges(param, fn) {
  return {
    vertexData: param.vertexData,
    adjacency: Data$RescriptDigraph.$$Map.map(param.adjacency, adj => Data$RescriptDigraph.$$Map.map(adj, fn)),
    nextId: param.nextId
  };
}

function filterVertex(param, fn) {
  let filtered = Data$RescriptDigraph.$$Map.filter(param.vertexData, fn);
  return {
    vertexData: filtered,
    adjacency: Data$RescriptDigraph.$$Map.map(Data$RescriptDigraph.$$Map.filter(param.adjacency, (k, param) => filtered.has(k)), adj => Data$RescriptDigraph.$$Map.filter(adj, (k, param) => filtered.has(k))),
    nextId: param.nextId
  };
}

function deleteVertex(param, vid) {
  let adjacency = param.adjacency;
  return {
    vertexData: Data$RescriptDigraph.$$Map.filter(param.vertexData, (k, param) => k !== vid),
    adjacency: (adjacency.delete(vid), Data$RescriptDigraph.$$Map.map(adjacency, adj => Data$RescriptDigraph.$$Map.filter(adj, (k, param) => k !== vid))),
    nextId: param.nextId
  };
}

function deleteEdge(param, from, to) {
  return {
    vertexData: param.vertexData,
    adjacency: Data$RescriptDigraph.$$Map.adjust(param.adjacency, from, adj => Data$RescriptDigraph.$$Map.$$delete(adj, to)),
    nextId: param.nextId
  };
}

function hasVertex(param, vid) {
  return param.vertexData.has(vid);
}

function hasEdge(param, from, to) {
  return Stdlib_Option.getOr(Stdlib_Option.map(param.adjacency.get(from), adj => adj.has(to)), false);
}

function vertexCount(param) {
  return param.vertexData.size;
}

function edgeCount(param) {
  return Stdlib_Array.reduce(param.adjacency.entries().toArray(), 0, (acc, param) => acc + param[1].size | 0);
}

function vertices(param) {
  return param.vertexData.entries().toArray();
}

function edges(param) {
  return param.adjacency.entries().toArray().flatMap(param => {
    let from = param[0];
    return param[1].entries().toArray().map(param => [
      from,
      param[0],
      param[1]
    ]);
  });
}

function successors(param, vid) {
  return Stdlib_Option.getOr(Stdlib_Option.map(param.adjacency.get(vid), adj => adj.entries().toArray()), []);
}

function predecessors(param, vid) {
  return Stdlib_Array.filterMap(param.adjacency.entries().toArray(), param => {
    let from = param[0];
    return Stdlib_Option.map(param[1].get(vid), edgeData => [
      from,
      edgeData
    ]);
  });
}

function outDegree(param, vid) {
  return Stdlib_Option.getOr(Stdlib_Option.map(param.adjacency.get(vid), adj => adj.size), 0);
}

function inDegree(param, vid) {
  return Stdlib_Array.reduce(param.adjacency.entries().toArray(), 0, (acc, param) => {
    if (param[1].has(vid)) {
      return acc + 1 | 0;
    } else {
      return acc;
    }
  });
}

function roots(g) {
  return vertices(g).filter(param => inDegree(g, param[0]) === 0);
}

function sinks(g) {
  return vertices(g).filter(param => outDegree(g, param[0]) === 0);
}

function bfs(g, start) {
  if (!hasVertex(g, start)) {
    return [];
  }
  let visited = new Map();
  visited.set(start, true);
  let frontier = [start];
  let result = {
    contents: []
  };
  while (frontier.length > 0) {
    let nextFrontier = {
      contents: []
    };
    frontier.forEach(vid => {
      let vdata = getVertex(g, vid);
      if (vdata !== undefined) {
        result.contents = result.contents.concat([[
            vid,
            Primitive_option.valFromOption(vdata)
          ]]);
        successors(g, vid).forEach(param => {
          let neighbor = param[0];
          if (!visited.has(neighbor)) {
            visited.set(neighbor, true);
            nextFrontier.contents = nextFrontier.contents.concat([neighbor]);
            return;
          }
          
        });
        return;
      }
      
    });
    frontier = nextFrontier.contents;
  };
  return result.contents;
}

function dfs(g, start) {
  if (!hasVertex(g, start)) {
    return [];
  }
  let visited = new Map();
  let result = {
    contents: []
  };
  let visit = vid => {
    if (visited.has(vid)) {
      return;
    }
    visited.set(vid, true);
    let vdata = getVertex(g, vid);
    if (vdata !== undefined) {
      result.contents = result.contents.concat([[
          vid,
          Primitive_option.valFromOption(vdata)
        ]]);
      successors(g, vid).forEach(param => visit(param[0]));
      return;
    }
    
  };
  visit(start);
  return result.contents;
}

function topoSort(g) {
  let inDegrees = new Map();
  vertices(g).forEach(param => {
    inDegrees.set(param[0], 0);
  });
  edges(g).forEach(param => {
    let to = param[1];
    inDegrees.set(to, Stdlib_Option.getOr(inDegrees.get(to), 0) + 1 | 0);
  });
  let queue = Stdlib_Array.filterMap(inDegrees.entries().toArray(), param => {
    if (param[1] === 0) {
      return param[0];
    }
    
  });
  let result = {
    contents: []
  };
  while (queue.length > 0) {
    let nextQueue = {
      contents: []
    };
    queue.forEach(vid => {
      let vdata = getVertex(g, vid);
      if (vdata !== undefined) {
        result.contents = result.contents.concat([[
            vid,
            Primitive_option.valFromOption(vdata)
          ]]);
        successors(g, vid).forEach(param => {
          let neighbor = param[0];
          let newDeg = Stdlib_Option.getOr(inDegrees.get(neighbor), 0) - 1 | 0;
          inDegrees.set(neighbor, newDeg);
          if (newDeg === 0) {
            nextQueue.contents = nextQueue.contents.concat([neighbor]);
            return;
          }
          
        });
        return;
      }
      
    });
    queue = nextQueue.contents;
  };
  if (result.contents.length === vertexCount(g)) {
    return result.contents;
  }
  
}

function hasCycle(g) {
  return Stdlib_Option.isNone(topoSort(g));
}

function reverse(param) {
  let vertexData = param.vertexData;
  let newAdj = new Map();
  vertexData.entries().toArray().forEach(param => {
    newAdj.set(param[0], new Map());
  });
  param.adjacency.entries().toArray().forEach(param => {
    let from = param[0];
    param[1].entries().toArray().forEach(param => {
      let edgeData = param[1];
      Stdlib_Option.map(newAdj.get(param[0]), toAdj => {
        toAdj.set(from, edgeData);
      });
    });
  });
  return {
    vertexData: vertexData,
    adjacency: newAdj,
    nextId: param.nextId
  };
}

function merge(g1, g2) {
  let idMap = new Map();
  let g = Stdlib_Array.reduce(vertices(g2), g1, (g, param) => {
    let newG = insertVertex(g, param[1]);
    idMap.set(param[0], newG.nextId - 1 | 0);
    return newG;
  });
  return Stdlib_Array.reduce(edges(g2), g, (g, param) => {
    let match = idMap.get(param[0]);
    let match$1 = idMap.get(param[1]);
    if (match !== undefined && match$1 !== undefined) {
      return insertEdge(g, match, match$1, param[2]);
    } else {
      return g;
    }
  });
}

function subgraph(g, vids) {
  let vidSet = new Map();
  vids.forEach(vid => {
    vidSet.set(vid, undefined);
  });
  return filterVertex(g, (vid, param) => vidSet.has(vid));
}

export {
  make,
  insertVertex,
  insertEdge,
  getVertex,
  getEdge,
  mapVertices,
  mapEdges,
  filterVertex,
  deleteVertex,
  deleteEdge,
  hasVertex,
  hasEdge,
  vertexCount,
  edgeCount,
  vertices,
  edges,
  successors,
  predecessors,
  outDegree,
  inDegree,
  roots,
  sinks,
  bfs,
  dfs,
  topoSort,
  hasCycle,
  reverse,
  merge,
  subgraph,
}
/* No side effect */
