// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Data from "./Data.res.mjs";
import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";

function make() {
  return {
    vertexData: new Map(),
    adjacency: new Map(),
    nextId: 0
  };
}

function insertVertex(param, vdata) {
  let nextId = param.nextId;
  return {
    vertexData: Data.$$Map.set(param.vertexData, nextId, vdata),
    adjacency: Data.$$Map.set(param.adjacency, nextId, new Map()),
    nextId: nextId + 1 | 0
  };
}

function insertEdge(param, from, to, edgeData) {
  return {
    vertexData: param.vertexData,
    adjacency: Data.$$Map.adjust(param.adjacency, from, map => Data.$$Map.set(map, to, edgeData)),
    nextId: param.nextId
  };
}

function getVertex(param, vid) {
  return param.vertexData.get(vid);
}

function getEdge(param, from, to) {
  return Stdlib_Option.flatMap(param.adjacency.get(from), map => map.get(to));
}

function mapVertices(param, fn) {
  return {
    vertexData: Data.$$Map.map(param.vertexData, fn),
    adjacency: param.adjacency,
    nextId: param.nextId
  };
}

function mapEdges(param, fn) {
  return {
    vertexData: param.vertexData,
    adjacency: Data.$$Map.map(param.adjacency, adj => Data.$$Map.map(adj, fn)),
    nextId: param.nextId
  };
}

function deleteVertex(param, vid) {
  let adjacency = param.adjacency;
  return {
    vertexData: Data.$$Map.filter(param.vertexData, (k, param) => k !== vid),
    adjacency: (adjacency.delete(vid), Data.$$Map.map(adjacency, adj => Data.$$Map.filter(adj, (k, param) => k !== vid))),
    nextId: param.nextId
  };
}

function deleteEdge(param, from, to) {
  let adjacency = param.adjacency;
  return {
    vertexData: param.vertexData,
    adjacency: (Stdlib_Option.map(adjacency.get(from), adj => adj.delete(to)), adjacency),
    nextId: param.nextId
  };
}

export {
  make,
  insertVertex,
  insertEdge,
  getVertex,
  getEdge,
  mapVertices,
  mapEdges,
  deleteVertex,
  deleteEdge,
}
/* No side effect */
